from enum import Enum


class TrackingState(str, Enum):
    INIT = "INIT"
    CAMERA_READY = "CAMERA_READY"
    TARGET_SELECTION = "TARGET_SELECTION"
    POINT_PROMPT = "POINT_PROMPT"
    CANDIDATE_TRACKING = "CANDIDATE_TRACKING"
    LEARNING_TARGET = "LEARNING_TARGET"
    LOCKED_TRACKING = "LOCKED_TRACKING"
    TRACKING = "TRACKING"
    STABLE = "STABLE"
    UNCERTAIN = "UNCERTAIN"
    LOST = "LOST"
    SEARCHING = "SEARCHING"
    REACQUIRED = "REACQUIRED"
    STOPPED = "STOPPED"
    ERROR = "ERROR"
